config/routes.rb
Blogger::Application.routes.draw do
  root to: 'articles#index'

  resources :articles do
    resources :comments
  end

  resources :tags
  

end

app/models/article.rb
class Article < ActiveRecord::Base
  default_scope -> { order(created_at: :desc) }
	has_many :comments, dependent: :destroy
	has_many :taggings, dependent: :destroy
	has_many :tags, through: :taggings
	mount_uploader :image, ArticleUploader
	validates :author_name, presence: {message: "is required"}, length: {maximum: 30}
	validates :title, presence: {message: "is required"}, length: {maximum: 230}
	validates :body, presence: {message: "is required"}, length: {maximum: 1600}
	validates :tag_list, length: {maximum: 230}
	validate  :image_size

	def tag_list=(tags_string)
		tag_names = tags_string.split(",").collect{|s| s.strip.downcase}.uniq
		new_or_found_tags = tag_names.collect { |name| Tag.find_or_create_by(name: name) }
  		self.tags = new_or_found_tags
	end

	def tag_list
		self.tags.collect do |tag|
			tag.name
		end.join(", ")
	end

private

  # Validates the size of an uploaded image.
  def image_size
    if image.size > 5.megabytes
      errors.add(:image, "(Select image with smaller file size)")
    end
  end

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  default_scope -> { order(created_at: :desc) }
  belongs_to :article
  validates :author_name, presence: {message: "is required"}, length: {maximum: 30}
  validates :body, presence: {message: "is required"}, length: {maximum: 200}
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  default_scope -> { order(name: :asc) }
	has_many :taggings, dependent: :destroy
	has_many :articles, through: :taggings
end

app/models/tagging.rb
class Tagging < ActiveRecord::Base
  belongs_to :tag
  belongs_to :article
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

	def index
		@articles = Article.all
	end

	def new
		@article = Article.new
	end

	def create
		@article = Article.new(article_params)
		if @article.save
			redirect_to article_path(@article)
		else
			render :new
		end
	end

	def show
		@article = Article.find(params[:id])
		@article_comments = @article.comments
		@comment = Comment.new
		@comment.article_id = @article.id
	end

	def destroy
		@article = Article.find(params[:id])
		@article.destroy
	end

private

	def article_params
  		params.require(:article).permit(:title, :body, :tag_list, :image, :author_name)
	end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	
	def create
		@comment = Comment.new(comment_params)
		@comment.article_id = params[:article_id]
		@comment.save
		redirect_to article_path(@comment.article)
	end

	def comment_params
	  params.require(:comment).permit(:author_name, :body)
	end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
	
	def index
		@tags = Tag.all
	end
	
	def show
		@tag = Tag.find(params[:id])
		@tag_articles = @tag.articles
	end

	def destroy
		@tag = Tag.find(params[:id])
		@tag.destroy
		flash.notice = "Tag '#{@tag.name}' deleted!"
		redirect_to tags_path
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
	
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/articles/_article.html.erb
<tr onclick="document.location='<%= article_path(article.id)%>'" style="cursor: pointer;">
  <td><p class="table-name"><%= truncate article.title, length: 130 %></p></td>
  <td><p><%= article.author_name %></p></td>
  <td><p><%= article.created_at.strftime('%b %d, %Y') %></p></td>
  <td><p><%= article.comments.count %></p></td>
</tr>

app/views/articles/_form.html.erb
<%= form_for(@article, html: {multipart: true}) do |f| %>
  <ul>
    <% @article.errors.full_messages.each do |error| %>
      <li><%= error %></li>
    <% end %>
  </ul>
  <div class="form-group">
    <%= f.label :author_name, "Your Name" %><span class="required-star">*</span>
    <%= f.text_field :author_name , class: "form-control", maxlength: "30", required: true %>
  </div>
  <div class="form-group">
    <%= f.label :title %><span class="required-star">*</span>
    <%= f.text_field :title, class: "form-control", maxlength: "230", required: true %>
  </div>
  <div class="form-group">
    <%= f.label :body, "Body Text" %><span class="required-star">*</span>
    <%= f.text_area :body, class: "form-control", rows: "10", maxlength: "1600", required: true %>
  </div>
  <div class="form-group">
    <%= f.label :tag_list, "Tags (Seperated by ',' )" %>
    <%= f.text_field :tag_list, placeholder: "ex: programming, rails, cooking", class: "form-control", maxlength: "230" %>
  </div>
  <div class="form-group">
    <%= f.label :image, "Add an image to your post" %>
    <%= f.file_field :image, accept: 'image/jpeg,image/gif,image/png', class: "btn btn-primary" %>
  </div>
  <div class="form-group">
    <a href="/articles" class="btn btn-lg btn-danger" id="cancel-button">Cancel</a>
    <%= f.submit "Create", class: "btn btn-lg btn-success", id: "submit-button" %>
  </div>
<% end %>

app/views/articles/index.html.erb
<% provide(:title, "All Posts") %> 

<div class="container">
  <div class="col-xs-12">
    <h1 class="header-text">All Posts</h1>
  </div>

  <div class="row">
    <div class="table-responsive col-md-12">
      <table class="table table-striped table-hover">
        <thead>
          <tr>
            <th>Title</th>
            <th>Author</th>
            <th>Created On</th>
            <th>Comments</th>
          </tr>
        </thead>
        <tbody>
          <%= render @articles%>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/articles/new.html.erb
<% provide(:title, "Create Post") %> 

<div class="container">
  <h1 class="header-text">Create Post</h1>

  <div class="row ">
    <div class="col-lg-6 mx-auto text-center">
      <%= render partial: 'form' %>
    </div>
  </div>
</div>

app/views/articles/show.html.erb
<% provide(:title, @article.title) %> 

<div class="container">
  <div class="row">
    <div class="col-md-12 text-center">
      <h1 class="header-text">"<%= @article.title %>" by <%= @article.author_name %></h1>
      <h4>Created on <%= @article.created_at.strftime("%b %d %Y")%></h4>
      <div class="col-md-6 mx-auto">
        <p><%= image_tag @article.image.url, class: "post-image" if @article.image? %></p>
      </div>
      <h2 id="article-body"><%= @article.body %></h2>
      <br>
      <h4 id="tags">
        Tags:
        <% @article.tags.each do |tag| %>
          <%= link_to tag.name, tag_path(tag) %>,
        <% end %>
      </h4>
    </div>
    <div class="col-md-12 mx-auto">
      <div class="col-md-6 mx-auto">
        <%= render partial: 'comments/form' %>
      </div>
      <h4>Comments (<%= @article_comments.size %>)</h4>
      <hr>
      <%= render @article_comments %>
    </div>
  </div>
</div>

app/views/comments/_comment.html.erb
<div class="media">
  <div class="media-body">
    <h5 class="mt-0"><%= comment.author_name %> <small>Posted on <%= comment.created_at.strftime('%b %d, %Y') %></small></h5>
    <%= comment.body %>
  </div>
</div>
<hr>

app/views/comments/_form.html.erb
<div id="comment-form">
  <div class="form-area"> 
    <%= form_for [ @article, @comment ] do |f| %>
      <br style="clear:both">
      <h3 style="margin-bottom: 25px; text-align: center;">Post a comment</h3>
      <div class="form-group">
        <%= f.label :author_name, "Your Name:" %>
        <%= f.text_field :author_name, class: "form-control", maxlength: "30", required: true %>
      </div>
      <div class="form-group">
        <%= f.label :body, "Comment:" %>
        <%= f.text_area :body, class: "form-control", id: "comment-text-area", maxlength: "200", rows: "2" %>
        <span class="help-block"><p id="characterLeft" class="help-block ">200 characters max</p></span>                    
      </div>
      <%= f.submit 'Submit', class: "btn btn-primary pull-right" %>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blogger | <%= yield(:title) %></title>

  <!-- Favicons -->
  <%= favicon_link_tag 'favicon.ico' %>
  <link rel="apple-touch-icon" href="apple-touch-icon.png">
  <link rel="icon" type="image/png" href="favicon-32x32.png" sizes="32x32" />
  <link rel="icon" type="image/png" href="favicon-16x16.png" sizes="16x16" />

  <!-- Meta Tags -->
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <%= csrf_meta_tags %>

  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css" integrity="sha384-/Y6pD6FV/Vv2HJnA6t+vslU6fwYXjCFtcEpHbNJ0lyAFsXTsjBbfaDjzALeQsN6M" crossorigin="anonymous">
  <link href="https://opensource.keycdn.com/fontawesome/4.7.0/font-awesome.min.css" rel="stylesheet">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
</head>
<body>
  <nav class="navbar navbar-expand-lg fixed-top navbar-dark bg-primary">
    <a class="navbar-brand" href="/">Blogger</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
      <ul class="navbar-nav navbar-right ml-auto">
        <li class="nav-item">
          <a class="nav-link" href="/">All Posts</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/articles/new">Create Post</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/tags">Search by Tags</a>
        </li>
      </ul>
    </div>
  </nav>

  <p class="flash">
    <%= flash.notice %>
  </p>

  <%= yield %>

  <nav class="navbar navbar-dark bg-primary" id="footer">
    <div class="container">
      <div class="text-left">
        <p id="copyright">Copyright © <a href="http://www.eric-gonzalez.com/" target="blank">Eric Gonzalez</a>, All Rights Reserved</p>
      </div>
      <div class="text-right" id="source-code">
        <a href="https://github.com/Twinpair/Blogger" target="blank"><i class="fa fa-github"></i> Source Code</a>
      </div>
    </div>
  </nav>

  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

  <!-- Bootstrap JS -->
  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js" integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4" crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js" integrity="sha384-h0AbiXch4ZDo7tp9hKZ4TsHbi047NrKGLO3SEJAg45jXxnGIfYzk4Si90RDIqNm1" crossorigin="anonymous"></script>
</body>
</html>

app/views/tags/_tag.html.erb
<tr onclick="document.location='<%= tag_path(tag.id)%>'" style="cursor: pointer;">
  <td><p class="table-name"><%= tag.name %></p></td>
  <td><p><%= tag.articles.count %></p></td>
</tr>

app/views/tags/index.html.erb
<% provide(:title, "All Tags") %> 

<div class="container">
  <div class="col-xs-12">
    <h1 class="header-text">All Tags</h1>
  </div>

  <div class="row">
    <div class="table-responsive col-md-12">
      <table class="table table-striped table-hover">
        <thead>
          <tr>
            <th>Tag Name</th>
            <th>Article Count</th>
          </tr>
        </thead>
        <tbody>
          <%= render @tags %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/tags/show.html.erb
<% provide(:title, @tag.name) %> 

<div class="container">
  <div class="col-xs-12">
    <h1 class="header-text">Articles Tagged with "<%= @tag.name %>"</h1>
  </div>

  <div class="row">
    <div class="table-responsive col-md-12">
      <table class="table table-striped table-hover">
        <thead>
          <tr>
            <th>Tag Name</th>
            <th>Article Count</th>
          </tr>
        </thead>
        <tbody>
          <%= render @tag_articles %>
        </tbody>
      </table>
    </div>
  </div>
</div>